### Data Cleaning, EDA, and initial preprocessing on main property transaction sales data from JPPH

In [223]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [224]:
data = pd.read_csv("data/kuala_lumpur_data.csv")
data.head()

,Property Type,District,Mukim,Scheme Name/Area,Road Name,"Month, Year of Transaction Date",Tenure,Land/Parcel Area,Unit,Main Floor Area,Unit,Unit Level,Transaction Price
0,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur,Kuala Lumpur Town Centre,JALAN CHERAS,JALAN KELIAN,January 2024,Freehold,293.378,sq.m,138.46,sq.m,,1600000
1,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur,Kuala Lumpur Town Centre,JALAN CHERAS,JALAN KELIAN,August 2024,Freehold,294.399,sq.m,102.1,sq.m,,1200000
2,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur,Kuala Lumpur Town Centre,JALAN CHERAS,JLN KELIAN,September 2021,Freehold,293.378,sq.m,139.82,sq.m,,1500000
3,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur,Kuala Lumpur Town Centre,KAW KASIPILLAY,JALAN PIPIT,October 2022,Freehold,441.852,sq.m,169.18,sq.m,,1550000
4,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur,Kuala Lumpur Town Centre,MILLION GARDEN,JALAN PIPIT,June 2024,Freehold,565.277,sq.m,144.93,sq.m,,2100000

In [225]:
data.columns = data.columns.str.strip().str.lower().str.replace(r'[ ,/]', '_', regex=True)
data.rename(columns={'month__year_of_transaction_date': 'month_year'}, inplace=True)
data['month_year'] = pd.to_datetime(data['month_year'], format='%B %Y')
data.columns

Index(['property_type', 'district', 'mukim', 'scheme_name_area', 'road_name',
       'month_year', 'tenure', 'land_parcel_area', 'unit', 'main_floor_area',
       'unit', 'unit_level', 'transaction_price'],
      dtype='str')

In [226]:
data['year'] = data['month_year'].dt.year
data.drop(columns='month_year', inplace=True)

In [227]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 25978 entries, 0 to 25977
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   property_type      25978 non-null  str
 1   district           25978 non-null  str
 2   mukim              25978 non-null  str
 3   scheme_name_area   25978 non-null  str
 4   road_name          25978 non-null  str
 5   tenure             25978 non-null  str
 6   land_parcel_area   25978 non-null  float64
 7   unit               25978 non-null  str
 8   main_floor_area    25978 non-null  str
 9   unit               25978 non-null  str
 10  unit_level         25978 non-null  str
 11  transaction_price  25978 non-null  int64
 12  year               25978 non-null  int32
dtypes: float64(1), int32(1), int64(1), str(10)
memory usage: 2.5 MB

In [228]:
data.nunique()

property_type          11
district                1
mukim                   9
scheme_name_area     1258
road_name            3632
tenure                  2
land_parcel_area     1723
unit                    1
main_floor_area      2741
unit                    2
unit_level             90
transaction_price    2147
year                    5
dtype: int64

In [229]:
data.drop('district', axis=1, inplace=True)

In [ ]:
data.columns

In [222]:
mask = data.iloc[:, 8] == '-'
data_no_mainfloor = data[mask].copy()
print(len(data_no_mainfloor))
data_no_mainfloor

19818

,property_type,mukim,scheme_name_area,road_name,tenure,land_parcel_area,unit,main_floor_area,unit,unit_level,transaction_price,year
5333,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),,Leasehold,57.0,sq.m,-,-,G,469000,2023
5334,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),,Freehold,197.0,sq.m,-,-,1,1260000,2024
5335,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),,Leasehold,104.0,sq.m,-,-,10,650000,2024
5336,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),,Leasehold,104.0,sq.m,-,-,6,580000,2025
5337,Condominium/Apartment,Kuala Lumpur Town Centre,2 HAMPSHIRE,,Freehold,310.0,sq.m,-,-,23,2000000,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
25973,Town House,Mukim Setapak,WANGSA METROVIEW,,Freehold,176.0,sq.m,-,-,1,560000,2021
25974,Town House,Mukim Setapak,WANGSA METROVIEW,,Freehold,176.0,sq.m,-,-,1,600000,2022
25975,Town House,Mukim Setapak,WANGSA METROVIEW,,Freehold,130.0,sq.m,-,-,1,395000,2025
25976,Town House,Mukim Setapak,WANGSA METROVIEW,,Freehold,176.0,sq.m,-,-,1,570000,2025
25977,Town House,Mukim Ulu Kelang,BB WANGSA MAJU TOWNHOUSE,,Leasehold,110.0,sq.m,-,-,G,700000,2022

In [192]:
data_no_mainfloor.nunique()

property_type           4
mukim                   8
scheme_name_area      975
road_name               1
tenure                  2
land_parcel_area      831
unit                    1
main_floor_area         1
unit                    1
unit_level             85
transaction_price    1870
year                    5
dtype: int64

In [193]:
data_no_mainfloor[['road_name', 'unit', 'main_floor_area']].groupby('road_name').value_counts()

road_name  unit  unit  main_floor_area
           sq.m  -     -                  19818
Name: count, dtype: int64

In [194]:
data_no_mainfloor.drop(['road_name', 'unit', 'main_floor_area'], axis=1, inplace=True)

In [195]:
data_no_mainfloor.nunique()

property_type           4
mukim                   8
scheme_name_area      975
tenure                  2
land_parcel_area      831
unit_level             85
transaction_price    1870
year                    5
dtype: int64

In [196]:
data_no_mainfloor['property_type'].unique()

<StringArray>
['Condominium/Apartment', 'Flat', 'Low-Cost Flat', 'Town House']
Length: 4, dtype: str

In [197]:
data_no_mainfloor['mukim'].value_counts()

mukim
Mukim Batu                  4955
Mukim Petaling              4114
Mukim Kuala Lumpur          4010
Mukim Setapak               3546
Kuala Lumpur Town Centre    2565
Mukim Ampang                 310
Mukim Ulu Kelang             230
Mukim Cheras                  88
Name: count, dtype: int64

In [198]:
data_mainfloor = data[~mask].copy()
data_mainfloor.head()

,property_type,mukim,scheme_name_area,road_name,tenure,land_parcel_area,unit,main_floor_area,unit,unit_level,transaction_price,year
0,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,JALAN CHERAS,JALAN KELIAN,Freehold,293.378,sq.m,138.46,sq.m,,1600000,2024
1,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,JALAN CHERAS,JALAN KELIAN,Freehold,294.399,sq.m,102.1,sq.m,,1200000,2024
2,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,JALAN CHERAS,JLN KELIAN,Freehold,293.378,sq.m,139.82,sq.m,,1500000,2021
3,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,KAW KASIPILLAY,JALAN PIPIT,Freehold,441.852,sq.m,169.18,sq.m,,1550000,2022
4,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,MILLION GARDEN,JALAN PIPIT,Freehold,565.277,sq.m,144.93,sq.m,,2100000,2024

In [199]:
data_mainfloor.nunique()

property_type           7
mukim                   9
scheme_name_area      370
road_name            3631
tenure                  2
land_parcel_area     1250
unit                    1
main_floor_area      2740
unit                    1
unit_level              9
transaction_price     967
year                    5
dtype: int64

In [200]:
data_mainfloor.drop('unit', axis=1, inplace=True)
data_mainfloor.head()

,property_type,mukim,scheme_name_area,road_name,tenure,land_parcel_area,main_floor_area,unit_level,transaction_price,year
0,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,JALAN CHERAS,JALAN KELIAN,Freehold,293.378,138.46,,1600000,2024
1,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,JALAN CHERAS,JALAN KELIAN,Freehold,294.399,102.1,,1200000,2024
2,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,JALAN CHERAS,JLN KELIAN,Freehold,293.378,139.82,,1500000,2021
3,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,KAW KASIPILLAY,JALAN PIPIT,Freehold,441.852,169.18,,1550000,2022
4,1 - 1 1/2 Storey Semi-Detached,Kuala Lumpur Town Centre,MILLION GARDEN,JALAN PIPIT,Freehold,565.277,144.93,,2100000,2024

In [201]:
data_mainfloor['mukim'].value_counts()

mukim
Mukim Batu                  1944
Mukim Kuala Lumpur          1645
Mukim Petaling              1461
Mukim Setapak                713
Kuala Lumpur Town Centre     183
Mukim Cheras                  90
Mukim Ampang                  70
Mukim Ulu Kelang              51
Mukim AMPang                   3
Name: count, dtype: int64

In [202]:
data_mainfloor[data_mainfloor['mukim'] == 'Mukim AMPang']

,property_type,mukim,scheme_name_area,road_name,tenure,land_parcel_area,main_floor_area,unit_level,transaction_price,year
1683,2 - 2 1/2 Storey Terraced,Mukim AMPang,KAW JLN AMPANG/AMPANG HILIR,PERSIARAN AMPANG,Freehold,264.000,163.69,,1750000,2023
20463,Detached,Mukim AMPang,KAW JLN AMPANG/AMPANG HILIR,JLN AMPANG HILIR,Leasehold,1258.900,297.01,,6400000,2023
20464,Detached,Mukim AMPang,KAW JLN AMPANG/AMPANG HILIR,PERSIARAN AMPANG,Freehold,1072.382,303.51,,5000000,2022

In [203]:
data_mainfloor.loc[data_mainfloor['mukim'] == 'Mukim AMPang', 'mukim'] = 'Mukim Ampang'
data_mainfloor['mukim'].value_counts()

mukim
Mukim Batu                  1944
Mukim Kuala Lumpur          1645
Mukim Petaling              1461
Mukim Setapak                713
Kuala Lumpur Town Centre     183
Mukim Cheras                  90
Mukim Ampang                  73
Mukim Ulu Kelang              51
Name: count, dtype: int64

In [204]:
data_mainfloor['unit_level'].unique()

<StringArray>
['    ', '1-Mar', '1-3', '1-2', 'G', '1-4', '2025-04-01 00:00:00', 'T', '2.5']
Length: 9, dtype: str

In [205]:
data_mainfloor.groupby('unit_level').size()

unit_level
                       6140
1-2                       4
1-3                       7
1-4                       1
1-Mar                     2
2.5                       1
2025-04-01 00:00:00       1
G                         3
T                         1
dtype: int64

In [206]:
mask2 = data_mainfloor['unit_level'].isin(['1-Mar', '1-3', '1-2', 'G', '1-4', '2025-04-01 00:00:00', 'T', '2.5'])
data_mainfloor[mask2]

,property_type,mukim,scheme_name_area,road_name,tenure,land_parcel_area,main_floor_area,unit_level,transaction_price,year
1272,2 - 2 1/2 Storey Semi-Detached,Mukim Kuala Lumpur,BERINGIN RESIDENCE TOWNHOUSE,JALAN BERINGIN,Freehold,270.0,351.68,1-Mar,4880000,2024
1488,2 - 2 1/2 Storey Semi-Detached,Mukim Petaling,DESA PETALING,JALAN 1/125E DESA VILLAS,Freehold,237.0,237,1-3,3200000,2024
1490,2 - 2 1/2 Storey Semi-Detached,Mukim Petaling,DESA PETALING,JALAN 5/125G,Freehold,253.0,253,1-3,3112000,2024
1611,2 - 2 1/2 Storey Semi-Detached,Mukim Ulu Kelang,BANDAR BARU WANGSA MAJU,JLN 8/27D,Leasehold,478.0,229.04,1-2,1700000,2024
1619,2 - 2 1/2 Storey Terraced,Kuala Lumpur Town Centre,JALAN BANGSAR,JLN TENGGIRI,Freehold,117.0,140.29,1-2,2200000,2024
1818,2 - 2 1/2 Storey Terraced,Mukim Batu,DESA PARK CITY (ADIVA),PERSIARAN RESIDEN,Freehold,129.0,167,1-2,2900000,2025
1853,2 - 2 1/2 Storey Terraced,Mukim Batu,DESA PARK CITY (NADIA),"PH19, JALAN PERSIARAN RESIDEN",Freehold,117.0,214,1-3,3200000,2025
1931,2 - 2 1/2 Storey Terraced,Mukim Batu,DESA PARK CITY (ZENIA),JALAN RESIDEN 2,Freehold,108.0,108,G,1850000,2024
1937,2 - 2 1/2 Storey Terraced,Mukim Batu,DESA PARK CITY (ZENIA),JLN RESIDEN 2,Freehold,126.0,259,1-3,3630000,2025
1982,2 - 2 1/2 Storey Terraced,Mukim Batu,DESA PARKCITY (CASAMAN),NO 2. CANGKAT INTISARI,Freehold,204.0,506,1-3,6400000,2025
3177,2 - 2 1/2 Storey Terraced,Mukim Kuala Lumpur,EAST RESIDENCES @ KLGCC,JALAN BUKIT KIARA 1,Leasehold,157.0,411,G,4600000,2025
3216,2 - 2 1/2 Storey Terraced,Mukim Kuala Lumpur,RESIDENSI MILLENIA,JLN DESA BAKTI 3,Freehold,385.0,385,1-4,3250000,2025
3217,2 - 2 1/2 Storey Terraced,Mukim Kuala Lumpur,RESIDENSI MILLENIA,JLN DESA BAKTI 3,Freehold,385.0,385,2025-04-01 00:00:00,3350000,2025
3218,2 - 2 1/2 Storey Terraced,Mukim Kuala Lumpur,RESIDENSI MILLENIA,JLN DESA BAKTI 3,Freehold,385.0,385,G,4900000,2025
3836,2 - 2 1/2 Storey Terraced,Mukim Petaling,BANDAR BARU SRI PETALING,JALAN 12/149L,Leasehold,273.0,273,1-2,1650000,2024
4860,2 - 2 1/2 Storey Terraced,Mukim Setapak,SUNWAY MONTANA,JALAN DESA MELAWATI,Freehold,201.0,327.47,T,1730000,2024
4861,2 - 2 1/2 Storey Terraced,Mukim Setapak,SUNWAY MONTANA,JALAN DESA MELAWATI,Freehold,201.0,327.47,1-3,1800000,2024
20819,Detached,Mukim Kuala Lumpur,KIARA HILLS,JALAN 32/70A,Freehold,621.0,682,1-Mar,6800000,2024
20820,Detached,Mukim Kuala Lumpur,KIARA HILLS,JALAN 32/70A,Freehold,696.0,682,1-3,6830000,2024
20893,Detached,Mukim Kuala Lumpur,TMN BUKIT TIARA,JALAN BUKIT TIARA 3,Freehold,372.0,372,2.5,4600000,2024

In [207]:
data_mainfloor.drop(columns='unit_level', inplace=True)

In [208]:
data_mainfloor['property_type'].unique()

<StringArray>
['1 - 1 1/2 Storey Semi-Detached',      '1 - 1 1/2 Storey Terraced',
 '2 - 2 1/2 Storey Semi-Detached',      '2 - 2 1/2 Storey Terraced',
                  'Cluster House',                       'Detached',
                 'Low-Cost House']
Length: 7, dtype: str

In [209]:
data_highrise = data_no_mainfloor
data_landed = data_mainfloor

In [210]:
data_highrise.head()

,property_type,mukim,scheme_name_area,tenure,land_parcel_area,unit_level,transaction_price,year
5333,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Leasehold,57.0,G,469000,2023
5334,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Freehold,197.0,1,1260000,2024
5335,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Leasehold,104.0,10,650000,2024
5336,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Leasehold,104.0,6,580000,2025
5337,Condominium/Apartment,Kuala Lumpur Town Centre,2 HAMPSHIRE,Freehold,310.0,23,2000000,2022

In [211]:
data_highrise['unit_level'].unique()

<StringArray>
[  'G',   '1',  '10',   '6',  '23',   'P',   '7',   '8',  '15',  '13',  '31',
  '30',  '29',  '26',  '22',  '24',  '19',   '4',   '3',   '2',   '5',  '3A',
  '28',  '27',  '02',  '05',   '9',  '21',  '12',  '11',  '16',  '20',  '18',
  '17',  '32',  '34',  '35',  '14',  '36',  '37',  '25',  '40',  '38', '13A',
  'LG',   'B', '1-5',  '42',  '43',  '41',  '39',  '33', '33A', '23A',  '54',
  '55',  '45',  '49',  '50',  '52',  '48',  '47',  '53',  '46',  '51',  '44',
 '53A',   'D', '1-4',  '57', '43A',  '09',  'MZ', '03A', '2-3',  'UG', '12B',
  '01', '31A',  '1A', '20.', '1-2', '1-3', '1&2', '2-4']
Length: 85, dtype: str

In [212]:
from utils import clean_floor

data_highrise['unit_level'] = data_highrise['unit_level'].apply(clean_floor)
data_highrise['unit_level'].unique()

array([ 0,  1, 10,  6, 23,  7,  8, 15, 13, 31, 30, 29, 26, 22, 24, 19,  4,
        3,  2,  5, 28, 27,  9, 21, 12, 11, 16, 20, 18, 17, 32, 34, 35, 14,
       36, 37, 25, 40, 38, 42, 43, 41, 39, 33, 54, 55, 45, 49, 50, 52, 48,
       47, 53, 46, 51, 44, 57])

In [213]:
sqm_to_sqft = 10.7639104
data_highrise['land_parcel_area'] = data_highrise['land_parcel_area'] * sqm_to_sqft
data_highrise

,property_type,mukim,scheme_name_area,tenure,land_parcel_area,unit_level,transaction_price,year
5333,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Leasehold,613.542893,0,469000,2023
5334,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Freehold,2120.490349,1,1260000,2024
5335,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Leasehold,1119.446682,10,650000,2024
5336,Condominium/Apartment,Kuala Lumpur Town Centre,1A STONOR APT (CONLAY COURT),Leasehold,1119.446682,6,580000,2025
5337,Condominium/Apartment,Kuala Lumpur Town Centre,2 HAMPSHIRE,Freehold,3336.812224,23,2000000,2022
...,...,...,...,...,...,...,...,...
25973,Town House,Mukim Setapak,WANGSA METROVIEW,Freehold,1894.448230,1,560000,2021
25974,Town House,Mukim Setapak,WANGSA METROVIEW,Freehold,1894.448230,1,600000,2022
25975,Town House,Mukim Setapak,WANGSA METROVIEW,Freehold,1399.308352,1,395000,2025
25976,Town House,Mukim Setapak,WANGSA METROVIEW,Freehold,1894.448230,1,570000,2025
25977,Town House,Mukim Ulu Kelang,BB WANGSA MAJU TOWNHOUSE,Leasehold,1184.030144,0,700000,2022

In [214]:
data_highrise.to_csv("data/highrise.csv", index=False)